### PR TITLE
Add text to comply with Apache naming guidelines

### PR DESCRIPTION
**Pull request by geomacy**
See http://www.apache.org/foundation/marks/pmcs.html#naming

In particular this part:
<quote>
Every product homepage and any overview download pages for the product
must include a prominent reference to the product as "Apache Foo
software", and must include a brief one sentence description of the
function of the software product itself.
</quote>

### CODE REVIEW

**Comment by geomacy** [comment]
I've made some adjustments and moved the description down as suggested by @rdowner. On my box now the front page looks like

image


and the download page like 

image

What do you think?

**Comment by geomacy** [comment]
hi @rdowner @tbouron could I ask for another review, what do you think of the look now?

**Comment by tbouron** [comment]
I'm also happy with this @geomacy !

**Comment by geomacy** [comment]
Thanks @rdowner @tbouron, I've merged this now and will have a look at pushing it to the website. Haven't done this before, we'll see how it goes. It will probably be the weekend though before I get to look at it...

**Pull request merged**
